//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyIPSWMinimal {
	
	
	public partial class Link {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.RadioButtonList rblOptions;
		
		protected System.Web.UI.WebControls.Label lblStep2;
		
		protected System.Web.UI.WebControls.DropDownList ddlVersion;
		
		protected System.Web.UI.WebControls.DropDownList ddlVersionOTA;
		
		protected System.Web.UI.WebControls.DropDownList ddliPhone;
		
		protected System.Web.UI.WebControls.DropDownList ddliPad;
		
		protected System.Web.UI.WebControls.DropDownList ddliPod;
		
		protected System.Web.UI.WebControls.DropDownList ddlWatch;
		
		protected System.Web.UI.WebControls.DropDownList ddlMac;
		
		protected System.Web.UI.WebControls.DropDownList ddlAudioAccessory;
		
		protected System.Web.UI.WebControls.DropDownList ddlAppleTV;
		
		protected System.Web.UI.WebControls.Label lblStep3;
		
		protected System.Web.UI.WebControls.Label lblSelectionComment;
		
		protected System.Web.UI.WebControls.Label lblSelection;
		
		protected System.Web.UI.WebControls.Button btnRetrieve;
		
		protected System.Web.UI.WebControls.Label tbData;
	}
}
